version: '3.8'

services:
  server:
    container_name: code-with-us-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - code-with-us
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client:
    container_name: code-with-us-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
      args:
        - VITE_BACKEND_URL=http://localhost:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - code-with-us
    ports:
      - "5173:5173"
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  code-with-us:
    driver: bridge
