[build]
builder = "DOCKERFILE"
dockerfilePath = "./server/Dockerfile"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
name = "code-nexus-server"
port = 3000

[service]
name = "code-nexus-client"
port = 5173 