[build]
builder = "DOCKERFILE"
dockerfilePath = "./docker-compose.yml"

[deploy]
startCommand = "docker-compose up"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
name = "code-nexus"
port = 3000 