services:
  - type: web
    name: code-with-us-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    dockerCommand: docker build -t code-with-us-server ./server
    envVars:
      - key: CORS_ORIGIN
        value: https://code-with-us-client.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: code-with-us-client
    env: node
    buildCommand: npm install
    startCommand: npm run preview
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    dockerCommand: docker build --build-arg VITE_BACKEND_URL=https://code-with-us-backend.onrender.com -t code-with-us-client ./client
    envVars:
      - key: VITE_BACKEND_URL
        value: https://code-with-us-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true 