services:
  - type: web
    name: code-nexus-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerCommand: docker build -t code-nexus-server ./server
    dockerContext: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://code-nexus-client.onrender.com
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: code-nexus-client
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerCommand: docker build --build-arg VITE_BACKEND_URL=https://code-nexus-backend.onrender.com -t code-nexus-client ./client
    dockerContext: ./client
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BACKEND_URL
        value: https://code-nexus-backend.onrender.com
    autoDeploy: true 